conversations/urls.py
from django.urls import path
from .views import *

app_name='conversations'

urlpatterns = [
    path('inbox/',inbox,name="inbox"),
    path('inbox/<int:profile_friend>', inbox, name="inbox_new_chat"),
    path('chatbox/<int:chat_id>', chatbox, name="chatbox"),
    path('delete/chat/<int:chat_id>', delete_chat, name="delete_chat"),
    path('delete/mesage/<int:message_id>', delete_message, name="delete_message"),

]

pages/urls.py
from django.urls import path

from .views import *

app_name = 'pages'

urlpatterns = [
    path('', index, name='index'),
    path('login/', login, name="login"),
    path('register/', register, name="register"),
    path('logout/', logout, name="logout"),
    path('profile/<int:profile_id>', profile, name="profile"),
    path('edit/',edit_profile,name="edit"),
    path('search/',search,name="search"),
    path('request/send/<int:to_profile_id>', send_request, name="send_request"),
    path('request/cancel/<int:to_profile_id>', cancel_request, name="cancel_request"),
    path('request/accept/<int:from_profile_id>', accept_friend_request, name="accept_request"),
    path('request/delete/<int:from_profile_id>', delete_friend_request, name="delete_request"),
    path('unfriend/<int:profile_id>', unfriend, name="unfriend"),

]

penpals_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('message/', include('conversations.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FKD</title>
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-md bg-dark navbar-dark">
        <div class="container">
            <a href="{% url 'pages:index' %}" class="navbar navbar-brand">FKD</a>
        </div>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{request.user.profile.get_absolute_url}}" class="nav-link">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'conversations:inbox' %}" class="nav-link">Inbox</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container mt-4">
    {% if messages %}
        {% for message in messages  %}

        {% if message.tags == 'error' %}
            <div class="alert alert-danger" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{message}}
            </div>
        {% else %}

        <div class="alert alert-{{message.tags}}" role="alert">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{message}}

        </div>

        {% endif %}

        {% endfor %}
    {% endif %}

        {% block content%}
        {% endblock content%}

    </div>

    {% if page_obj.has_other_pages %}

    <ul class="pagination justify-content-center">
        {% for p in page_obj.paginator.page_range  %}

            {% if page_obj.number == p %}
            <li class="page-item active">
                <a href="?{{ s }}page={{p}}" class="page-link">{{p}}</a>
            </li>
            {% else %}
            <li class="page-item ">
                <a href="?{{ s }}page={{p}}" class="page-link">{{p}}</a>
            </li>

            {% endif %}
        {% endfor %}
    </ul>
    {% endif %}

    <footer class="bg-dark text-white mt-auto">
        <div class="container py-4">
            <p class="text-center"> Copyright &copy; FKD 2020</p>
        </div>
    </footer>

    <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

    {% block js%}
    {% endblock js%}
</body>
</html>