conversations/urls.py
from django.urls import path
from .views import *

app_name='conversations'

urlpatterns = [
    path('inbox/',inbox,name="inbox"),
    path('inbox/<int:profile_friend>', inbox, name="inbox_new_chat"),
    path('chatbox/<int:chat_id>', chatbox, name="chatbox"),
    path('delete/chat/<int:chat_id>', delete_chat, name="delete_chat"),
    path('delete/mesage/<int:message_id>', delete_message, name="delete_message"),

]

pages/urls.py
from django.urls import path

from .views import *

app_name = 'pages'

urlpatterns = [
    path('', index, name='index'),
    path('login/', login, name="login"),
    path('register/', register, name="register"),
    path('logout/', logout, name="logout"),
    path('profile/<int:profile_id>', profile, name="profile"),
    path('edit/',edit_profile,name="edit"),
    path('search/',search,name="search"),
    path('request/send/<int:to_profile_id>', send_request, name="send_request"),
    path('request/cancel/<int:to_profile_id>', cancel_request, name="cancel_request"),
    path('request/accept/<int:from_profile_id>', accept_friend_request, name="accept_request"),
    path('request/delete/<int:from_profile_id>', delete_friend_request, name="delete_request"),
    path('unfriend/<int:profile_id>', unfriend, name="unfriend"),

]

penpals_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('message/', include('conversations.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/includes/_sidebar.html
<div class="col-lg-3 col-md-3 col-sm-6 mx-auto">
    <div class="card bg-light" style="max-width:30rem;">
        {% if profile.photo %}
        <img src="{{profile.photo.url}}" class="card-img-top mx-auto rounded-circle">
        {% else %}
        <img src="/media/user.png" class="card-img-top mx-auto rounded-circle">
        {% endif %}
        <div class="card-body text-center">
            <h4 class="card-title">
                <a href="{{profile.get_absolute_url}}"> {{profile}}</a>
            </h4>
            {% if request.user == profile.user %}
            Welcome, {{profile.user}} <p><a href="{% url 'pages:logout' %}"> Logout</a> | <a href="{% url 'conversations:inbox' %}">Inbox</a></p>
            {% elif request.user.is_anonymous%}
            <p><a href="{% url 'pages:register' %}"> Register</a> | <a href="{% url 'pages:login' %}"> Login</a></p>
            {% endif %}
        </div>

    </div>
</div>