pages/urls.py
from django.urls import path

from .views import *

app_name = 'pages'

urlpatterns = [
    path('', index, name='index'),
    path('login/', login, name="login"),
    path('register/', register, name="register"),
    path('logout/', logout, name="logout"),
    path('profile/<int:profile_id>', profile, name="profile"),
    path('edit/',edit_profile,name="edit"),
    path('search/',search,name="search"),
    path('request/send/<int:to_profile_id>', send_request, name="send_request"),
    path('request/cancel/<int:to_profile_id>', cancel_request, name="cancel_request"),
    path('request/accept/<int:from_profile_id>', accept_friend_request, name="accept_request"),
    path('request/delete/<int:from_profile_id>', delete_friend_request, name="delete_request"),
    path('unfriend/<int:profile_id>', unfriend, name="unfriend"),

]

penpals_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('message/', include('conversations.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/templates/pages/edit.html
{% extends 'pages/base.html' %}

{% block content %}

<div class="col-sm-8 mx-auto mb-5">
    <h2>Edit your profile</h2>

    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors  %}
        <p>{{error}}</p>
    {% endfor %}
    </div>
    {% endif %}

    <form method="post" enctype="multipart/form-data" autocomplete="off">
        {% csrf_token %}
        {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{field}}
            {% for error in field.errors %}
            <p style="color:red">{{error}}</p>
            {% endfor %}
        </p>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Save</button>

    </form>


</div>

{% endblock content %}

pages/templates/pages/index.html
{% extends 'pages/base.html' %}


 {% block content%}
   <div class="row">
        {% include 'pages/includes/_sidebar.html'%}

        <div class="col-lg-9 col-md-9 col-sm-12">
            <div class="card bg-light">
                <div class="card-header text-center">Search for People</div>
                <div class="card-body">
                    <form action="{% url 'pages:search' %}" method="get">
                        <div class="form-group">
                            <label for="langspeaks">Speaks</label>
                            <input type="text" name="speaks" value="{{ request.GET.speaks }}" class="form-control" id="langspeaks" placeholder="value1, value2">
                        </div>
                        <div class="form-group">
                            <label for="langlearning">Is learning</label>
                            <input type="text" name="learning" value="{{ request.GET.learning }}"  class="form-control" id="langlearning" placeholder="value1, value2">
                        </div>
                        <button type="submit" class="btn btn-info">Search</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="row">
            {% for u in page_obj %}
                <div class="col-md-3 col-sm-6">
                    <div class="card">
                        <img src="{{u.photo.url}}" class="card-img-top mx-auto">
                        <div class="card-body">
                            <h5 class="card-title text-center"><a href="{{u.get_absolute_url}}">{{u}}</a></h5>
                            <p class="card-text">
                                <span><strong>Speaks: </strong>{{u.speaks}}</span></br>
                                <span><strong>Is learning: </strong>{{u.is_learning}}</span></br>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>
{% endblock content%}

pages/templates/pages/login.html
{% extends 'pages/base.html' %}

{% block content %}

<div class="col-sm-8 mx-auto">
    <h2>Login</h2>

    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors  %}
        <p>{{error}}</p>
    {% endfor %}
    </div>
    {% endif %}

    <form method="post" autocomplete="off">
        {% csrf_token %}
        {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{field}}
            {% for error in field.errors %}       
            <p style="color:red">{{error}}</p>
            {% endfor %}
        </p>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Log in</button>

    </form>


</div>

{% endblock content %}

pages/templates/pages/profile.html
{% extends 'pages/base.html' %}

{% block content %}

<div class="row">
    {% include 'pages/includes/_sidebar.html' %}

    <div class="col-md-9 col-sm-12">
        {% if request.user.profile.id == profile.id %}
        <div class="float-right">
            <a href="{% url 'pages:edit' %}" class="btn btn-info">Edit profile</a>
        </div>


        {% elif request.user.is_authenticated%}
            {% if btn_text == 'not_friend' %}
            <div class="float-right">
                <a href="{% url 'pages:send_request' profile.id %}" class="btn btn-primary">Add Friend</a>
            </div>

            {% elif btn_text == 'request_sent' %}
            <div class="float-right">
                <a href="{% url 'pages:cancel_request' profile.id %}" class="btn btn-warning">Cancel Request</a>
            </div>
            {% endif %}

        {% endif %}

        <h3>{{profile.user}}</h3>
        <div class="my-4">
            <h6>{{profile.first}} {{profile.last}} | {{profile.user.email}}</h6>
            <h6>Speaks: {{profile.speaks}}</h6>
            <h6>Is learning: {{profile.is_learning}}</h6>
        </div>


        {% if friends %}
        <div class="table-responsive">
            <table class="table">
                <caption>List of People</caption>
                <thead>
                    <tr>
                        <th>Username</th>
                        <th>Email</th>
                    </tr>
                </thead>
                <tbody>
                    {% for f in friends  %}
                    <tr>
                        <td>{{f}}</td>
                        <td>{{f.user.email}}</td>
                        {% if request.user.profile.id == profile.id %}
                        <td><a href="{% url 'pages:unfriend' f.id %}" class="btn btn-danger confirm-delete" id="{{f}}" data-toggle="modal" data-target="#confirmModal">Unfriend</a></td>
                        {% endif %}
                    </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>

        {% endif %}


        {% if request.user.profile.id == profile.id and received_requests %}
         <div class="table-responsive">
             <table class="table">
                 <caption>Received friend requests: </caption>
                 <tbody>
                    {% for r_request in received_requests %}
                        <tr>
                            <td>{{r_request}}</td>
                            <td><a class="btn btn-primary" href="{% url 'pages:accept_request' r_request.from_profile.id %}">Accept</a></td>
                            <td><a class="btn btn-danger" href="{% url 'pages:delete_request' r_request.from_profile.id %}">Delete</a></td>
                        </tr>
                    {% endfor %}

                 </tbody>
             </table>
         </div>
        {% endif %}

    </div>
</div>

<div class="modal fade" id="confirmModal" tabindex="-1" caller-id="" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal" id="confirmButtonModal">Unfriend</button>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

{% block js %}
<script type="text/javascript">

    $(document).on('click','.confirm-delete', function(){
        $("#confirmModal").attr("caller-id",$(this).attr("id"));
        $("div.modal-body").text("Are you sure you want to unfriend "+ $(this).attr("id")+"?");
    });

    $(document).on('click','#confirmButtonModal', function(){
        var caller = $("#confirmButtonModal").closest(".modal").attr("caller-id");
        window.location = $("#".concat(caller)).attr("href");
    });



</script>
{% endblock js %}

pages/templates/pages/register.html
{% extends 'pages/base.html' %}

{% block content %}

<div class="col-sm-8 mx-auto mb-5">
    <h2>Register</h2>

    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors  %}
        <p>{{error}}</p>
    {% endfor %}
    </div>
    {% endif %}

    <form method="post" autocomplete="off">
        {% csrf_token %}
        {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{field}}
            {% if field.help_text %}
            <small style="color:gray">{{field.help_text}}</small>
            {% endif %}
            {% for error in field.errors %}       
            <p style="color:red">{{error}}</p>
            {% endfor %}
        </p>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Register</button>

    </form>


</div>

{% endblock content %}