conversations/urls.py
from django.urls import path
from .views import *

app_name='conversations'

urlpatterns = [
    path('inbox/',inbox,name="inbox"),
    path('inbox/<int:profile_friend>', inbox, name="inbox_new_chat"),
    path('chatbox/<int:chat_id>', chatbox, name="chatbox"),
    path('delete/chat/<int:chat_id>', delete_chat, name="delete_chat"),
    path('delete/mesage/<int:message_id>', delete_message, name="delete_message"),

]

pages/urls.py
from django.urls import path

from .views import *

app_name = 'pages'

urlpatterns = [
    path('', index, name='index'),
    path('login/', login, name="login"),
    path('register/', register, name="register"),
    path('logout/', logout, name="logout"),
    path('profile/<int:profile_id>', profile, name="profile"),
    path('edit/',edit_profile,name="edit"),
    path('search/',search,name="search"),
    path('request/send/<int:to_profile_id>', send_request, name="send_request"),
    path('request/cancel/<int:to_profile_id>', cancel_request, name="cancel_request"),
    path('request/accept/<int:from_profile_id>', accept_friend_request, name="accept_request"),
    path('request/delete/<int:from_profile_id>', delete_friend_request, name="delete_request"),
    path('unfriend/<int:profile_id>', unfriend, name="unfriend"),

]

penpals_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('message/', include('conversations.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/models.py
from django.db import models
from pages.models import Profile


class Chat(models.Model):
    def __str__(self):
        return f'{self.id}'


class Message(models.Model):
    content = models.CharField(max_length=250)
    date = models.DateTimeField(auto_now_add=True)
    profile = models.ForeignKey(Profile, related_name='from_profile', on_delete=models.CASCADE)
    chat = models.ForeignKey(Chat, related_name='get_msg', on_delete=models.CASCADE)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ['date']


class Chat_members(models.Model):
    chat = models.ForeignKey(Chat, related_name='members', on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, related_name='chats', on_delete=models.CASCADE)
    last_viewed = models.DateTimeField(blank=True, null=True)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return f'chat id: {self.chat} user:{self.profile.user} last_viewed:{self.last_viewed} deleted:{self.deleted}'

conversations/forms.py
from django import forms
from .models import Message


class MessageForm(forms.ModelForm):
    content = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = Message
        fields = ['content']

conversations/views.py
from django.shortcuts import render, redirect
from .models import *
from django.utils import timezone
from .forms import MessageForm


def inbox(request, profile_friend=None):
    profile = request.user.profile
    friends = profile.friends.all()

    if profile_friend is not None:
        p2 = friends.filter(id=profile_friend).first()
        chats_deleted = Chat_members.objects.filter(profile=profile, deleted=True).values_list('chat_id', flat=True)
        if chats_deleted:
            chat_with_friend = Chat_members.objects.filter(chat_id__in=chats_deleted, profile_id=p2.id).first()

            if chat_with_friend:
                member = Chat_members.objects.get(chat_id=chat_with_friend.chat_id, profile=profile)
                member.deleted = False
                member.save()
                return redirect('conversations:inbox')

        new_chat = Chat()
        new_chat.save()
        m1 = Chat_members(chat=new_chat, profile=profile, deleted=False, last_viewed=timezone.now())
        m2 = Chat_members(chat=new_chat, profile=p2, deleted=False, last_viewed=timezone.now())
        m1.save()
        m2.save()
        return redirect('conversations:inbox')

    chats_ids = profile.chats.all().values_list('chat_id', flat=True)
    chats = Chat.objects.filter(id__in=chats_ids)
    chatting_with = []
    unread = []

    for c in chats:
        profile_chat_member = c.members.get(profile=profile)
        if profile_chat_member.deleted == False:
            friend_chat_member = c.members.exclude(profile=profile).first()
            chatting_with.append(friend_chat_member)
            friends = friends.exclude(user=friend_chat_member.profile.user)

            if c.get_msg.count() > 0:
                m_date = c.get_msg.values('date').latest('date')
                lv_date = c.members.filter(profile=profile).values('last_viewed').first()
                if m_date['date'] > lv_date['last_viewed']:
                    msg_count = c.get_msg.filter(date__gt=lv_date['last_viewed']).count()
                    unread.append(msg_count)
                else:
                    unread.append(False)
            else:
                unread.append(False)

    context = {
        'profile': profile,
        'friends': friends,
        'chat_details': zip(chatting_with, unread),
    }

    return render(request, 'conversations/inbox.html', context)


def chatbox(request, chat_id):
    profile = request.user.profile
    form = MessageForm()
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            new_msg = form.save(commit=False)
            new_msg.profile = profile
            new_msg.chat_id = chat_id
            new_msg.save()
            return redirect('conversations:chatbox', chat_id=chat_id)
    messages = Message.objects.filter(chat_id=chat_id)
    last_viewed = Chat_members.objects.filter(chat_id=chat_id).filter(profile=profile)
    last_viewed.update(last_viewed=timezone.now())

    context = {
        'profile': profile,
        'chat_id': chat_id,
        'form': form,
        'msg': messages
    }

    return render(request, 'conversations/chatbox.html', context)


def delete_chat(request, chat_id):
    chat = Chat.objects.get(id=chat_id)
    members = chat.members.all()

    for m in members:
        if m.profile == request.user.profile:
            profile = m
        else:
            friend = m

    if profile.deleted == False:
        profile.deleted = True
        profile.save()
    if friend.deleted == True:
        chat.delete()

    return redirect('conversations:inbox')


def delete_message(request, message_id):
    msg = Message.objects.get(id=message_id)
    msg.delete()
    return redirect('conversations:chatbox', chat_id=msg.chat_id)

conversations/templates/conversations/chatbox.html
{% extends 'pages/base.html' %}

{% block content %}

<div class="row">
    {% include 'pages/includes/_sidebar.html' %}
    <div class="col-md-9 col-sm-12">

        <div id="messageFeed" class="p-3">
            {% for m in msg %}
            <div class="card {% if request.user.profile == m.profile  %} ml-auto text-light bg-dark {% endif %}" style="width: 20rem;">
                <div class="card-header font-weight-bold">
                    {{m.profile}} | {{m.date}}
                    {% if request.user.profile == m.profile %}
                        <a href="{% url 'conversations:delete_message' m.id %}" class="close text-light">
                            <span>&times;</span>
                        </a>
                    {% endif %}
                </div>
                <div class="card-body">
                    {{m}}
                </div>
            </div>
            {% endfor %}
        </div>

        <form method="post" autocomplete="off">
            {% csrf_token %}
            <div class="input-group mb-3">
            {% for field in form  %}
                {{field}}
            {% endfor %}
            <button type="submit" class="btn btn-outline-primary">Send</button>
            </div>

        </form>

    </div>
</div>
{% endblock content %}

 {% block js %}
 <script>
      var d = $('#messageFeed');
      d.scrollTop(d.prop("scrollHeight"));

      $('html,body').animate({scrollTop:$(document).height()},'slow');

 </script>

 {% endblock js %}

conversations/templates/conversations/inbox.html
{% extends 'pages/base.html' %}

{% block content %}

<div class="row">
    {% include 'pages/includes/_sidebar.html' %}
    <div class="col-md-9 col-sm-12">

        <div class="table-responsive">
            <table class="table">
                <caption>List of ongoing chats </caption>
                <thead>
                    <tr>
                        <th>Chat</th>
                        <th>Unread</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cd,u in chat_details  %}
                    <tr>

                        <td>
                            <a href="{% url 'conversations:chatbox' cd.chat_id %}">
                            {{forloop.counter}} Chat with {{cd.profile}}
                            </a>
                        </td>

                        <td>
                            {% if u != False %}
                                <h5><span class="badge badge-primary badge-pill">{{u}}</span></h5>
                            {% else %}
                                <p> - </p>
                            {% endif %}
                        </td>

                        <td>
                            <a href="{% url 'conversations:delete_chat' cd.chat_id %}" class="btn btn-outline-danger">Delete chat</a>
                        </td>

                    </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% if friends %}
        <div class="table-responsive">
            <table class="table">
                <caption>Start a new chat with: </caption>
                <thead>
                    <tr>
                        <th>Username</th>
                        <th>Email</th>
                    </tr>
                </thead>
                <tbody>
                    {% for f in friends  %}
                        <tr>
                            <td>{{f}}</td>
                            <td>{{f.user.email}}</td>
                            {% if request.user.profile.id == profile.id %}
                            <td><a href="{% url 'conversations:inbox_new_chat' f.id %}" class="btn btn-outline-info" >Start chatting</a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}